"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProfileRouter = void 0;
const express_1 = require("express");
const CompleteProfile_1 = require("../controller/profile/CompleteProfile");
const verify_1 = require("../middleware/verify");
const stepProfile_1 = require("../controller/profile/stepProfile");
const get_completeProfile_1 = require("../controller/profile/get-completeProfile");
const get_Allcompleteprofile_1 = require("../controller/profile/get-Allcompleteprofile");
const profileupdate_1 = require("../controller/profile/profileupdate");
const paymentupdate_1 = require("../controller/profile/paymentupdate");
const get_Payment_1 = require("../controller/profile/get-Payment");
const getProfileById_1 = require("../controller/profile/getProfileById");
const backgrounded_1 = require("../controller/profile/backgrounded");
exports.ProfileRouter = (0, express_1.Router)();
exports.ProfileRouter.post("/profile", CompleteProfile_1.createProfile);
exports.ProfileRouter.get("/getCompleteProfile/:userId", get_completeProfile_1.getCompleteProfile);
exports.ProfileRouter.post("/createBankCard", verify_1.protect, stepProfile_1.createBankCard);
exports.ProfileRouter.get("/getAllProfiles", get_Allcompleteprofile_1.getAllProfiles);
exports.ProfileRouter.put("/updateProfile/:userId", profileupdate_1.updateProfile);
exports.ProfileRouter.put("/paymentupdate/:userId", paymentupdate_1.Paymentupdate);
exports.ProfileRouter.get("/getbankcard/:userId", get_Payment_1.getUpdate);
exports.ProfileRouter.post("/updatecover", backgrounded_1.updateCoverImage);
exports.ProfileRouter.get("/profiles/:id", getProfileById_1.getProfileById);
